# Unsloth Zoo - Utilities for Unsloth
# Copyright 2023-present Daniel Han-Chen, Michael Han-Chen & the Unsloth team. All rights reserved.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""The compiled cache must never execute bytes it did not generate.

`create_new_function` writes generated source into a working-directory-relative
cache and imports it back, so whatever is in that file runs. Two things made
that fail open on the ordinary single-process path:

* `write_file` swallowed every write failure and reported success, so a cache
  file whose own mode refused the rewrite was left in place and imported.
* the sha256 gate before the import only had an expected digest when a process
  group was initialised, so a single process had nothing to compare against.

`install_to_cache` in temporary_patches/moe_utils.py had the same shape: the
copy into the cache was wrapped in `except Exception: pass`, and the copy is
then loaded with `exec_module`.

Getting content into the cache directory is a local prerequisite, not something
a model repo can do on its own, but a dataset directory, an output directory or
a mode-preserving archive extraction all reach the working directory. These
tests keep every one of those paths landing on generated bytes or on nothing.
"""

from __future__ import annotations

import importlib.util
import os
import shutil
import stat
import sys
import tempfile
import warnings

import pytest

from unsloth_zoo import compiler
from unsloth_zoo.temporary_patches import moe_utils

# A marker written into os.environ, so a planted module that runs is visible
# even when its definitions are never called.
_MARKER = "UNSLOTH_TEST_PLANTED_CACHE_EXECUTED"

_PLANTED_SOURCE = (
    "import os\n"
    f"os.environ[{_MARKER!r}] = '1'\n"
    "def probe():\n"
    "    return 'planted'\n"
)
_GENUINE_SOURCE = "def probe():\n    return 'genuine'\n"


@pytest.fixture(autouse = True)
def _sandbox(tmp_path, monkeypatch):
    """Keep the cache, the temp fallback and sys.modules inside this test.

    `tempfile.tempdir` matters: the recovery path resolves its node-local cache
    through `tempfile.gettempdir()`, and left alone that is the real shared
    /tmp rather than the sandbox.
    """
    monkeypatch.setattr(compiler, "UNSLOTH_COMPILE_USE_TEMP", False)
    monkeypatch.setattr(tempfile, "tempdir", str(tmp_path / "tempdir"))
    os.makedirs(tmp_path / "tempdir", exist_ok = True)
    # setenv, not delenv: a planted module that runs sets this itself, and
    # delenv records nothing to restore when the variable is already absent, so
    # one failure would otherwise leak the marker into the rest of the session.
    monkeypatch.setenv(_MARKER, "0")
    yield
    for name in list(sys.modules):
        if name.startswith("UnslothFailClosedProbe") or name.startswith(
            "unsloth_cache_UnslothFailClosedProbe"
        ):
            del sys.modules[name]


@pytest.fixture
def cache_dir(tmp_path, monkeypatch):
    """An isolated persistent cache directory, restored to writable on teardown."""
    location = tmp_path / "unsloth_compiled_cache"
    location.mkdir()
    monkeypatch.setattr(compiler, "UNSLOTH_COMPILE_LOCATION", str(location))
    try:
        yield location
    finally:
        # A test that drops write permission has to give it back, or pytest's
        # own tmp_path cleanup is the thing that fails.
        for root, directories, _files in os.walk(location):
            for directory in directories:
                os.chmod(os.path.join(root, directory), 0o700)
        os.chmod(location, 0o700)


def _emit(name, source = _GENUINE_SOURCE):
    """create_new_function() as the ordinary single-process call sites reach it."""
    return compiler.create_new_function(name, source, "math", [])


def _plant(cache_dir, name, mode):
    path = cache_dir / f"{name}.py"
    path.write_text(_PLANTED_SOURCE)
    os.chmod(path, mode)
    return path


def _planted_ran():
    return os.environ.get(_MARKER, "0") == "1"


@pytest.mark.skipif(os.name != "posix", reason = "POSIX file permissions")
def test_planted_read_only_cache_file_is_not_executed(cache_dir):
    """The core case: a 0444 cache file is replaced, never imported.

    The in-place rewrite raises PermissionError on the file, but the directory
    is ours, so os.replace lands the generated source anyway.
    """
    name = "UnslothFailClosedProbeReadOnly"
    planted = _plant(cache_dir, name, 0o444)

    module = _emit(name)

    assert not _planted_ran(), "the planted cache file was imported and executed"
    assert module.probe() == "genuine"
    assert "planted" not in planted.read_text()
    assert "def probe():" in planted.read_text()


@pytest.mark.skipif(os.name != "posix", reason = "POSIX file permissions")
def test_victim_writable_planted_cache_file_is_overwritten(cache_dir):
    """Already-safe behaviour that has to stay: a writable file is rewritten."""
    name = "UnslothFailClosedProbeWritable"
    planted = _plant(cache_dir, name, 0o644)

    module = _emit(name)

    assert not _planted_ran()
    assert module.probe() == "genuine"
    assert "planted" not in planted.read_text()


def test_generated_cache_file_is_written_and_imported(cache_dir):
    """The ordinary path: generate, write, import, and stay idempotent."""
    name = "UnslothFailClosedProbeGenuine"

    module = _emit(name)
    written = (cache_dir / f"{name}.py").read_text()

    assert module.probe() == "genuine"
    assert "__UNSLOTH_VERSIONING__" in written

    # A second call has to reach the same bytes rather than trip the new gate.
    again = _emit(name)
    assert again.probe() == "genuine"
    assert (cache_dir / f"{name}.py").read_text() == written


@pytest.mark.skipif(os.name != "posix", reason = "POSIX file permissions")
def test_read_only_cache_directory_still_falls_back(cache_dir):
    """Already-safe behaviour that has to stay: an unwritable directory recovers.

    get_lock() cannot create `.locks/` there, and the recovery is a node-local
    temp cache rather than an error.
    """
    name = "UnslothFailClosedProbeReadOnlyDir"
    os.chmod(cache_dir, 0o500)

    module = _emit(name)

    assert module.probe() == "genuine"
    assert not (cache_dir / f"{name}.py").exists()
    assert os.path.realpath(module.__file__).startswith(
        os.path.realpath(tempfile.gettempdir())
    )


@pytest.mark.skipif(os.name != "posix", reason = "POSIX file permissions")
def test_unlandable_rewrite_over_planted_bytes_is_not_imported(cache_dir, monkeypatch):
    """When even the replacement cannot land, the write must report failure.

    This is the fail-open path itself: `write_file` used to log and return
    success, and the caller went straight on to import the file. Windows reaches
    it for real, because MoveFileEx honours the destination's read-only
    attribute where os.replace on POSIX does not.
    """
    name = "UnslothFailClosedProbeUnlandable"
    planted = _plant(cache_dir, name, 0o444)

    def cannot_replace(function_location, new_write_bytes):
        raise PermissionError("simulated replacement failure")

    monkeypatch.setattr(compiler, "_replace_compiled_cache_file", cannot_replace)

    module = _emit(name)

    assert not _planted_ran(), "the planted cache file was imported and executed"
    assert module.probe() == "genuine"
    # Untouched, and the module came from the node-local temp cache instead.
    assert planted.read_text() == _PLANTED_SOURCE
    assert os.path.realpath(module.__file__).startswith(
        os.path.realpath(tempfile.gettempdir())
    )


def test_write_decision_carries_a_digest_without_a_process_group(cache_dir):
    """The digest gate has to be armed when no process group exists.

    Without this, `_verify_cache_digest_under_lock` returns immediately and the
    bytes are imported unverified.
    """
    location = str(cache_dir / "UnslothFailClosedProbeDigest.py")

    should_write, digest = compiler._compiled_cache_decision(
        location, _GENUINE_SOURCE, True,
    )

    assert should_write is True
    assert digest is not None


def test_digest_verification_rejects_bytes_we_did_not_write(cache_dir):
    """The gate itself: mismatched bytes raise rather than reaching the import."""
    location = cache_dir / "UnslothFailClosedProbeGate.py"
    location.write_text(_GENUINE_SOURCE)
    _should_write, digest = compiler._compiled_cache_decision(
        str(location), _GENUINE_SOURCE, True,
    )
    location.write_text(_PLANTED_SOURCE)

    with pytest.raises(RuntimeError, match = "changed after"):
        compiler._verify_cache_digest_under_lock(str(location), digest)

    assert not _planted_ran()


def test_cache_file_swapped_after_the_write_is_not_imported(cache_dir, monkeypatch):
    """Plant between the write and the first import, which needs no permissions.

    Replacing the file after `import unsloth_zoo` and before the first use hits
    any uid, root included, so the write-side repair alone is not enough.
    """
    name = "UnslothFailClosedProbeSwapped"
    real_write = compiler._write_compiled_cache_file
    swapped = []

    def swap_after_write(function_location, new_write_bytes):
        real_write(function_location, new_write_bytes)
        # Once only: the recovery below writes too, and planting into that as
        # well would test a cache nothing can repair instead of this one.
        if not swapped:
            swapped.append(function_location)
            with open(function_location, "w") as file:
                file.write(_PLANTED_SOURCE)

    monkeypatch.setattr(compiler, "_write_compiled_cache_file", swap_after_write)

    module = _emit(name)

    assert swapped, "the write path under test was never reached"
    assert not _planted_ran(), "the swapped cache file was imported and executed"
    assert module.probe() == "genuine"


@pytest.mark.skipif(os.name != "posix", reason = "POSIX file permissions")
def test_read_only_moe_utils_cache_copy_is_replaced(tmp_path, monkeypatch):
    """install_to_cache() must land its copy over a read-only destination."""
    location = tmp_path / "moe_cache_replaceable"
    location.mkdir()
    monkeypatch.setenv("UNSLOTH_COMPILE_LOCATION", str(location))
    planted = location / "moe_utils.py"
    planted.write_text(_PLANTED_SOURCE)
    os.chmod(planted, 0o444)

    installed = moe_utils.install_to_cache(moe_utils.__file__, "moe_utils.py")

    with open(moe_utils.__file__, "rb") as handle:
        assert planted.read_bytes() == handle.read()
    assert installed is True


@pytest.mark.skipif(os.name != "posix", reason = "POSIX file permissions")
def test_unreplaceable_moe_utils_cache_copy_is_not_loaded(tmp_path, monkeypatch):
    """When the copy cannot land, the planted file must not be executed.

    There is always a safe answer here, because every caller falls back to the
    definitions in the package module.
    """
    location = tmp_path / "moe_cache_readonly"
    location.mkdir()
    planted = location / "moe_utils.py"
    planted.write_text(_PLANTED_SOURCE)
    os.chmod(planted, 0o444)
    os.chmod(location, 0o500)
    monkeypatch.setenv("UNSLOTH_COMPILE_LOCATION", str(location))
    monkeypatch.setattr(moe_utils, "_CACHED_MOE_UTILS_MODULE", None)
    monkeypatch.setattr(moe_utils, "_CACHED_FORWARD_MOE_BACKEND", None)
    monkeypatch.delitem(sys.modules, "unsloth_cached_moe_utils", raising = False)

    try:
        # Recorded rather than asserted with pytest.warns, so the assertions
        # that matter are reached whether or not anything warned.
        with warnings.catch_warnings(record = True) as caught:
            warnings.simplefilter("always")
            installed = moe_utils.install_to_cache(moe_utils.__file__, "moe_utils.py")

        assert moe_utils._load_cached_moe_utils_module() is None
        assert moe_utils.get_forward_moe_backend() is moe_utils.forward_moe_backend
        assert not _planted_ran(), "the planted cache copy was imported and executed"
        assert planted.read_text() == _PLANTED_SOURCE

        assert installed is False
        assert [entry for entry in caught if "does not match" in str(entry.message)]

        # install_to_cache() runs at import time, so the report itself must not
        # be what fails the import under a consumer's warnings-as-errors filter.
        with warnings.catch_warnings():
            warnings.simplefilter("error")
            assert moe_utils.install_to_cache(
                moe_utils.__file__, "moe_utils.py",
            ) is False
    finally:
        os.chmod(location, 0o700)
        sys.modules.pop("unsloth_cached_moe_utils", None)


def test_install_to_cache_survives_a_cache_it_cannot_create(tmp_path, monkeypatch):
    """A cache path that cannot exist at all reports failure without raising.

    Nothing lands and nothing is there to compare, so there is no destination to
    report on, only a False to keep the import going.
    """
    blocker = tmp_path / "not_a_directory"
    blocker.write_text("")
    monkeypatch.setenv("UNSLOTH_COMPILE_LOCATION", str(blocker / "cache"))

    with warnings.catch_warnings():
        warnings.simplefilter("error")
        assert moe_utils.install_to_cache(moe_utils.__file__, "moe_utils.py") is False


def test_moe_utils_cache_copy_loads_when_it_matches(tmp_path, monkeypatch):
    """The verification must not break the copy the MoE backends rely on."""
    location = tmp_path / "moe_cache_genuine"
    monkeypatch.setenv("UNSLOTH_COMPILE_LOCATION", str(location))
    monkeypatch.setattr(moe_utils, "_CACHED_MOE_UTILS_MODULE", None)
    monkeypatch.setattr(moe_utils, "_CACHED_FORWARD_MOE_BACKEND", None)
    monkeypatch.delitem(sys.modules, "unsloth_cached_moe_utils", raising = False)

    try:
        assert moe_utils.install_to_cache(moe_utils.__file__, "moe_utils.py") is True
        copy = moe_utils._load_cached_moe_utils_module()
        assert copy is not None
        assert copy is not moe_utils
        assert moe_utils.get_forward_moe_backend() is copy.forward_moe_backend
    finally:
        sys.modules.pop("unsloth_cached_moe_utils", None)


@pytest.mark.skipif(os.name != "posix", reason = "POSIX file permissions")
def test_foreign_bytes_are_reported_rather_than_accepted(cache_dir):
    """The write-side helpers: absent and generated are fine, other bytes are not."""
    location = str(cache_dir / "UnslothFailClosedProbeForeign.py")
    generated = _GENUINE_SOURCE.encode("utf-8")

    assert compiler._compiled_cache_file_is_foreign(location, generated) is False
    with open(location, "wb") as file:
        file.write(generated)
    assert compiler._compiled_cache_file_is_foreign(location, generated) is False
    with open(location, "wb") as file:
        file.write(_PLANTED_SOURCE.encode("utf-8"))
    assert compiler._compiled_cache_file_is_foreign(location, generated) is True

    # And the replacement path lands the generated bytes over a read-only file.
    os.chmod(location, 0o444)
    compiler._write_compiled_cache_file(location, generated)
    assert compiler._compiled_cache_file_is_foreign(location, generated) is False
    # Readable, so a shared cache directory is not permanently narrowed, but
    # never writable by anyone else, which is what would allow a re-plant.
    assert stat.S_IMODE(os.stat(location).st_mode) == 0o644


def _plant_bytecode_over(source_path, payload_source):
    """Compile payload_source into the pyc CPython would load for source_path.

    UNCHECKED_HASH is the point: CPython accepts such a pyc without ever
    comparing it to the .py beside it, so the source can stay byte-identical to
    what the digest check expects while the bytecode carries something else.
    """
    import py_compile

    payload = source_path.parent / "planted_payload.py"
    payload.write_text(payload_source)
    bytecode_location = importlib.util.cache_from_source(str(source_path))
    os.makedirs(os.path.dirname(bytecode_location), exist_ok = True)
    py_compile.compile(
        str(payload),
        cfile = bytecode_location,
        dfile = str(source_path),
        invalidation_mode = py_compile.PycInvalidationMode.UNCHECKED_HASH,
    )
    payload.unlink()
    return bytecode_location


def test_planted_bytecode_beside_expected_source_is_not_executed(cache_dir):
    """A cache holding the expected source plus a planted pyc must not run it.

    The digest covers the .py. Without dropping the bytecode the source verifies
    clean, no rewrite happens, and CPython executes the pyc instead.
    """
    name = "UnslothFailClosedProbeBytecode"

    # Phase 1: let the real generator write the canonical source, license header
    # and all, so phase 2 plants against bytes the digest will accept.
    first = _emit(name)
    assert first.probe() == "genuine"
    source_path = cache_dir / f"{name}.py"
    canonical = source_path.read_text()

    bytecode_location = _plant_bytecode_over(source_path, _PLANTED_SOURCE)
    assert os.path.isfile(bytecode_location)

    # Phase 2: a fresh import of the same name, with the source untouched.
    sys.modules.pop(name, None)
    module = _emit(name)

    assert source_path.read_text() == canonical, "the source was never the thing under attack"
    assert not _planted_ran(), "the planted cache bytecode was executed"
    assert module.probe() == "genuine"


def test_planted_bytecode_beside_moe_utils_cache_copy_is_not_executed(tmp_path, monkeypatch):
    """Same vector through the MoE cache copy, which execs the file directly."""
    location = tmp_path / "unsloth_compiled_cache"
    location.mkdir()
    monkeypatch.setattr(moe_utils, "_get_compile_location", lambda: str(location))

    # A copy identical to the package file, which is what the comparison accepts.
    package_file = os.path.abspath(moe_utils.__file__)
    cache_copy = location / "moe_utils.py"
    shutil.copyfile(package_file, cache_copy)

    _plant_bytecode_over(cache_copy, _PLANTED_SOURCE)

    sys.modules.pop("unsloth_cached_moe_utils", None)
    moe_utils._CACHED_MOE_UTILS_MODULE = None
    moe_utils._load_cached_moe_utils_module()

    assert not _planted_ran(), "the planted moe_utils cache bytecode was executed"
