#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright 2026-present the Unsloth AI Inc. team. All rights reserved.

"""Fails when `exec`/`eval`/`compile` is handed a string built by interpolation.

The pattern this exists for is the one PR unslothai/unsloth-zoo#1083 removed:

    exec(f"import transformers.models.{model_type}.modeling_{model_type}")

`model_type` came off a downloaded config.json, so a hostile model repo reached an
`exec`. Bare `exec(source)` where `source` is generated by `inspect.getsource` is
normal and heavily used here, so it is NOT flagged - what is flagged is a first
argument that is an f-string, a string concatenation, a `%` format or a `.format()`
call, because that is the shape where a value becomes syntax.

Reviewed exceptions live in `dynamic_exec_allowlist.json` next to this file. Entries
are keyed on (path, enclosing qualname, sha256 of the normalised call source) rather
than a line number, so they survive edits elsewhere in the file but not edits to the
call itself: change the call and you have to re-justify it.

Stdlib only, so it can run in a lint job that installs nothing.

Usage:
    python scripts/lint_dynamic_exec.py                 # check the package
    python scripts/lint_dynamic_exec.py --self-test     # check the checker
    python scripts/lint_dynamic_exec.py --update        # rewrite the allowlist
    python scripts/lint_dynamic_exec.py --paths a.py b.py
"""

from __future__ import annotations

import argparse
import ast
import hashlib
import json
import sys
from pathlib import Path


SINKS = ("exec", "eval", "compile")

REPO_ROOT = Path(__file__).resolve().parents[1]
ALLOWLIST_PATH = Path(__file__).resolve().parent / "dynamic_exec_allowlist.json"

# Directories scanned by default. Tests are excluded: they legitimately keep the
# removed exec/eval around as an oracle to prove the replacement matches it.
DEFAULT_TARGETS = ("unsloth_zoo", "unsloth", "studio", "scripts")


def _relative(path: Path) -> str:
    """Repo-relative where possible; absolute for the self-test's temp files.

    Always forward slashes: the allowlist is committed, and a Windows checkout that
    regenerated it with backslashes would rewrite every entry.
    """
    try:
        return path.relative_to(REPO_ROOT).as_posix()
    except ValueError:
        return path.as_posix()


def _is_interpolated(node: ast.AST) -> str | None:
    """Returns why `node` is a built string, or None if it is not one."""
    if isinstance(node, ast.JoinedStr):
        # An f-string with no placeholders is just a literal.
        if any(isinstance(v, ast.FormattedValue) for v in node.values):
            return "f-string"
        return None
    if isinstance(node, ast.BinOp):
        if isinstance(node.op, ast.Mod):
            return "%-format"
        if isinstance(node.op, ast.Add):
            return "string concatenation"
    if isinstance(node, ast.Call):
        function = node.func
        if isinstance(function, ast.Attribute) and function.attr in ("format", "join"):
            return f".{function.attr}()"
    return None


def _sink_name(function: ast.AST) -> str | None:
    """The sink this call target names, if any.

    Both `exec(...)` and `builtins.exec(...)` execute. Matching only `ast.Name` meant
    the second form passed the lint with zero findings.
    """
    if isinstance(function, ast.Name) and function.id in SINKS:
        return function.id
    if isinstance(function, ast.Attribute) and function.attr in SINKS:
        if isinstance(function.value, ast.Name) and function.value.id == "builtins":
            return f"builtins.{function.attr}"
    return None


def _source_argument(node: ast.Call, sink: str) -> ast.AST | None:
    """The source argument of a sink call, whether positional or by keyword.

    `exec` and `eval` take their source positional-only, so for those it is always
    `args[0]`. `compile` does not: its signature is
    `compile(source, filename, mode, ...)` with no `/`, so
    `compile(source = f"y = {x}", filename = "<x>", mode = "exec")` compiles exactly
    the same payload with `node.args` empty. Checking only `args[0]` meant that call
    was skipped entirely. `studio/backend/core/inference/tools.py` already resolves
    sink arguments this way.
    """
    if node.args:
        return node.args[0]
    if sink.rpartition(".")[2] == "compile":
        for keyword in node.keywords:
            if keyword.arg == "source":
                return keyword.value
    return None


class _Visitor(ast.NodeVisitor):
    def __init__(self, path: Path):
        self.path = path
        self.scope: list[str] = []
        self.findings: list[dict] = []
        # name -> reason, for locals bound to a built string in the current scope.
        self.tainted: list[dict[str, str]] = [{}]

    def _qualname(self) -> str:
        return ".".join(self.scope) if self.scope else "<module>"

    def _enter(self, node):
        self.scope.append(node.name)
        # A fresh scope: a name built in one function says nothing about the same name
        # in another.
        self.tainted.append({})
        self.generic_visit(node)
        self.tainted.pop()
        self.scope.pop()

    visit_FunctionDef = _enter
    visit_AsyncFunctionDef = _enter
    visit_ClassDef = _enter

    def visit_Assign(self, node: ast.Assign):
        """Tracks `payload = f"...{x}..."` so `exec(payload)` is still caught.

        One level of local indirection, which is all it took to defeat the previous
        version: moving the interpolation onto the line above is a two-line refactor
        that leaves the vulnerability shape exactly as it was. Rebinding a tracked name
        to something that is not a built string clears it, so this does not accumulate
        false positives.
        """
        reason = _is_interpolated(node.value)
        for target in node.targets:
            if not isinstance(target, ast.Name): continue
            if reason is None:
                self.tainted[-1].pop(target.id, None)
            else:
                self.tainted[-1][target.id] = f"{reason} via `{target.id}`"
        self.generic_visit(node)

    def visit_Call(self, node: ast.Call):
        sink = _sink_name(node.func)
        argument = _source_argument(node, sink) if sink is not None else None
        if argument is not None:
            reason = _is_interpolated(argument)
            if reason is None and isinstance(argument, ast.Name):
                reason = self.tainted[-1].get(argument.id)
            if reason is not None:
                self.findings.append(
                    {
                        "path": _relative(self.path),
                        "qualname": self._qualname(),
                        "sink": sink,
                        "reason": reason,
                        "line": node.lineno,
                        "hash": _call_hash(node),
                    }
                )
        self.generic_visit(node)


def _call_hash(node: ast.Call) -> str:
    """Hashes the call, canonicalised through `ast.unparse`.

    Line numbers drift whenever anything above the call changes; the call itself does
    not. Unparsing means reindenting, rewrapping or reflowing the call does not
    invalidate a justification, while changing what is interpolated does.
    """
    return hashlib.sha256(ast.unparse(node).encode("utf-8")).hexdigest()[:16]


def scan_file(path: Path) -> list[dict]:
    # A hard CI gate must not fall over on something that is not a readable file. A
    # dangling symlink, a directory named `*.py`, or a symlink to one all reach here
    # through rglob and raise out of read_text, failing the build for a reason that has
    # nothing to do with dynamic execution.
    try:
        source = path.read_text(encoding = "utf-8", errors = "replace")
    except OSError:
        return []
    try:
        tree = ast.parse(source, filename = str(path))
    except (SyntaxError, ValueError):
        # compileall in the same lint job is what reports unparseable files. ValueError
        # covers a source containing a NUL byte, which ast.parse rejects separately.
        return []
    visitor = _Visitor(path)
    try:
        visitor.visit(tree)
    except RecursionError:
        # A deeply nested literal can exhaust the stack during the walk, after parse
        # succeeded. Report nothing rather than taking the gate down; compileall still
        # sees the file.
        return []
    return visitor.findings


def scan(paths: list[Path]) -> list[dict]:
    findings = []
    for path in sorted(paths):
        findings.extend(scan_file(path))
    return findings


def collect_paths(targets: list[str]) -> list[Path]:
    paths = []
    for target in targets:
        root = REPO_ROOT / target
        if root.is_file() and root.suffix == ".py":
            paths.append(root)
        elif root.is_dir():
            # `is_file()` on each hit, so a directory named `foo.py` and a symlink that
            # points at one are skipped rather than read.
            paths.extend(
                p for p in root.rglob("*.py")
                if p.is_file() and "tests" not in p.relative_to(REPO_ROOT).parts
            )
    return paths


def load_allowlist() -> dict[str, dict]:
    if not ALLOWLIST_PATH.exists():
        return {}
    data = json.loads(ALLOWLIST_PATH.read_text())
    return {key_of(entry): entry for entry in data.get("allowed", [])}


def key_of(finding: dict) -> str:
    """Identity of a reviewed call: where it is, and what it is.

    The hash alone is not an identity. Two different call sites with byte-identical
    source share a hash, so approving one approved the other, and copying an
    allowlisted call into a function with attacker-controlled inputs inherited its
    justification without review. The location is half of what was reviewed, so it is
    half of the key.
    """
    return f"{finding['path']}::{finding['qualname']}::{finding['hash']}"


def write_allowlist(findings: list[dict], reason: str) -> None:
    existing = load_allowlist()
    allowed = []
    for finding in findings:
        previous = existing.get(key_of(finding), {})
        allowed.append(
            {
                "path": finding["path"],
                "qualname": finding["qualname"],
                "sink": finding["sink"],
                "kind": finding["reason"],
                "hash": finding["hash"],
                "reason": previous.get("reason", reason),
            }
        )
    allowed.sort(key = lambda e: (e["path"], e["qualname"], e["hash"]))
    ALLOWLIST_PATH.write_text(
        json.dumps(
            {
                "_comment": (
                    "Reviewed exec/eval/compile calls whose first argument is a built "
                    "string. Keyed on a hash of the call's own source, so editing the "
                    "call requires re-reviewing it. Regenerate with "
                    "scripts/lint_dynamic_exec.py --update, then replace every REVIEW "
                    "ME with why the interpolated value cannot be attacker controlled."
                ),
                "allowed": allowed,
            },
            indent = 2,
        )
        + "\n"
    )


# --- self test ---------------------------------------------------------------

_BAD = """
def f(model_type):
    exec(f"import transformers.models.{model_type}")
    eval("torch." + name)
    compile("x = %s" % value, "<x>", "exec")
    exec("a.{}.b".format(name))
    compile(source = f"y = {value}", filename = "<x>", mode = "exec")
"""

_GOOD = """
import inspect

def f(cls):
    source = inspect.getsource(cls)
    exec(source, globals())
    eval(compile(source, "<x>", "eval"))
    exec(f"plain f-string with no placeholders")
    module.exec(f"{name}")          # not the builtin
    exec()                          # no arguments
"""


def self_test() -> int:
    import tempfile

    failures = []
    with tempfile.TemporaryDirectory() as directory:
        bad = Path(directory) / "bad.py"
        bad.write_text(_BAD)
        findings = scan_file(bad)
        kinds = sorted(f["reason"] for f in findings)
        if kinds != ["%-format", ".format()", "f-string", "f-string", "string concatenation"]:
            failures.append(f"expected all four shapes plus the keyword call, got {kinds}")
        if any(f["qualname"] != "f" for f in findings):
            failures.append(f"qualname wrong: {[f['qualname'] for f in findings]}")

        good = Path(directory) / "good.py"
        good.write_text(_GOOD)
        clean = scan_file(good)
        if clean:
            failures.append(f"false positives: {clean}")

        # The hash must ignore reformatting but not a changed interpolation.
        one = Path(directory) / "one.py"
        one.write_text('def f(x):\n    exec(f"import {x}")\n')
        two = Path(directory) / "two.py"
        two.write_text('def f(x):\n    exec(\n        f"import {x}"\n    )\n')
        three = Path(directory) / "three.py"
        three.write_text('def f(x):\n    exec(f"import os; {x}")\n')
        h1 = scan_file(one)[0]["hash"]
        h2 = scan_file(two)[0]["hash"]
        h3 = scan_file(three)[0]["hash"]
        if h1 != h2:
            failures.append("reformatting changed the hash")
        if h1 == h3:
            failures.append("changing the interpolation did not change the hash")

    for failure in failures:
        print(f"self-test: {failure}", file = sys.stderr)
    if failures:
        print(f"FAIL: {len(failures)} self-test failure(s)", file = sys.stderr)
        return 1
    print("self-test: ok")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description = __doc__)
    parser.add_argument("--self-test", action = "store_true")
    parser.add_argument(
        "--update", action = "store_true", help = "rewrite the allowlist from the current tree"
    )
    parser.add_argument(
        "--paths",
        nargs = "*",
        default = None,
        help = "files or directories to scan (default: the package)",
    )
    args = parser.parse_args()

    if args.self_test:
        return self_test()

    targets = args.paths if args.paths else list(DEFAULT_TARGETS)
    findings = scan(collect_paths(targets))

    if args.update:
        write_allowlist(findings, reason = "REVIEW ME")
        print(f"wrote {len(findings)} entries to {ALLOWLIST_PATH.name}")
        return 0

    allowlist = load_allowlist()
    unreviewed = [f for f in findings if key_of(f) not in allowlist]
    pending = [
        entry
        for entry in allowlist.values()
        if entry.get("reason", "").strip().upper() in ("", "REVIEW ME")
    ]
    # Staleness is only meaningful over the whole tree: with --paths the scan is a
    # subset, so every entry outside it would look stale.
    seen = {key_of(f) for f in findings}
    stale = [] if args.paths else [entry for key, entry in allowlist.items() if key not in seen]

    for finding in unreviewed:
        print(
            f"{finding['path']}:{finding['line']}: {finding['sink']}() is handed a "
            f"{finding['reason']} (in {finding['qualname']})",
            file = sys.stderr,
        )
    for entry in pending:
        print(
            f"{entry['path']}: {entry['sink']}() in {entry['qualname']} is allowlisted "
            f"but has no justification",
            file = sys.stderr,
        )
    for entry in stale:
        print(
            f"{entry['path']}: allowlist entry for {entry['sink']}() in "
            f"{entry['qualname']} no longer matches any call - re-run --update",
            file = sys.stderr,
        )

    if unreviewed or pending or stale:
        print(
            f"\nFAIL: {len(unreviewed)} unreviewed, {len(pending)} unjustified, "
            f"{len(stale)} stale.\n"
            f"Fix the call, or run --update and write down why the interpolated value "
            f"cannot be attacker controlled.",
            file = sys.stderr,
        )
        return 1

    print(f"ok: {len(findings)} interpolated dynamic-execution call(s), all reviewed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
